# action.yaml
name: "erddap-deploy"
description: "Run a series of checks on an erddap configuration repository.
  This action is intended to be run prior to deploying an erddap instance."
inputs:
  datasets_xml:
    description: "Path to the datasets.xml file to be checked.
      It could be a glob expression."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Dependencies
      run: pip install ${{ github.action_path }}
      shell: bash
    - name: Run checks
      run: erddap_checks "${{ inputs.datasets_xml }}" test
      shell: bash
