# test-datasets-xml.yaml
---
name: "erddap-sync-datasets-xml"
description: "Run a series of checks on an erddap configuration repository.
  This action is intended to be run prior to deploying an erddap instance."
inputs:
  datasets_xml:
    description: "Path to the datasets.xml file to be checked.
      It could be a glob expression."
    required: false
    default: "**/datasets.xml|**/datasets.d/*.xml"
  recursive:
    description: "If true, subdirectories will be searched for datasets.xml
      files."
    required: false
    default: "true"
  active_dataset_xml:
    description: "Path to the active datasets.xml file."
    required: false
    default: "/usr/local/tomcat/content/erddap/datasets.xml"
  bigParentDirectory:
    description: "The big parent directory to sync the datasets.xml file to."
    required: false
    default: "{bigParentDirectory}"
  container_name:
    description: "The container to sync the datasets.xml file to."
    required: true
  repo:
    description: "The repository to sync the datasets.xml file to."
    required: false
    default: "${{ secrets.github_repository }}"
  branch:
    description: "The branch to sync the datasets.xml file to."
    required: false
    default: "${{ github.ref }}"
  local_repo_path:
    description: "The local path within the container where the present
      repository is cloned."
    required: false
    default: "/datasets-xml-repo"
  hard_flag:
    description: "Generate hard flags on datasets changes."
    required: false
    default: true
  hard_flag_dir:
    description: "The directory to store the hard flags."
    required: false
    default: "{bigParentDirectory}/erddap/hardFlags"
  ssh_host:
    description: "The ssh host to connecto the erddap server."
    required: true
  ssh_username:
    description: "The ssh user to connecto the erddap server."
    required: true
  ssh_key:
    description: "The ssh key to connecto the erddap server."
    required: true
  ssh_port:
    description: "The ssh port to connecto the erddap server."
    required: false
    default: 22
runs:
  using: "composite"
  steps:
    - name: Sync ERDDAP
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        shell: bash
        script: |
          docker exec
          $(docker ps --filter name=${{ inputs.container_name }} -q)
          erddap_deploy
          --datasets-xml "${{ inputs.datasets_xml }}"
          ${{ inputs.recursive && '--recursive'  || ''}}
          --active-dataset-xml ${{ inputs.active_dataset_xml }}
          --big-parent-directory ${{ inputs.bigParentDirectory }}
          sync
          --repo ${{ inputs.repo }}
          --branch ${{ inputs.branch }}
          --local-repo-path ${{ inputs.local_repo_path }}
          ${{ inputs.hard_flag && '--hard-flag' || '' }}
          --hard-flag-dir ${{ inputs.hard_flag_dir }}
