name: "Sync ERDDAP datasets.xml file to remote server"
description: "Update remote datasets.xml file on an docker container ERDDAP
  server via SSH."
inputs:
  datasets_xml:
    description: "Path to the datasets.xml file to be checked.
      It could be a glob expression."
    required: false
  recursive:
    description: "If true, subdirectories will be searched for datasets.xml
      files."
    required: false
  active_dataset_xml:
    description: "Path to the active datasets.xml file."
    required: false
  bigParentDirectory:
    description: "The big parent directory to sync the datasets.xml file to."
    required: false
  container_name:
    description: "The container to sync the datasets.xml file to."
    required: true
  repo_url:
    description: "The repository url to sync the datasets.xml file from."
    required: false
    default: "${{ github.repositoryURL }}"
  branch:
    description: "The branch to sync the datasets.xml file from."
    required: false
    default: "${{ github.ref_name }}"
  pull:
    description: "If true, the action will pull the repository before syncing."
    required: false
    default: true
  local_repo_path:
    description: "The local path within the container where the present
      repository is cloned."
    required: false
  hard_flag:
    description: "Generate hard flags on datasets changes."
    required: false
    default: true
  hard_flag_dir:
    description: "The directory to store the hard flags."
    required: false
  monitor:
    description: "If true, the action will sync the monitoring of the ERDDAP
      server."
    required: false
  ssh_host:
    description: "The ssh host to connecto the erddap server."
    required: true
  ssh_username:
    description: "The ssh user to connecto the erddap server."
    required: true
  ssh_key:
    description: "The ssh key to connecto the erddap server."
    required: true
  ssh_port:
    description: "The ssh port to connecto the erddap server."
    required: false
    default: 22
  sudo:
    description: "If true, the action will run the command with sudo."
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Update ERDDAP dataset.xml
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_username }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        script: |
          ${{ inputs.sudo && 'sudo ' || '' }}\
          docker exec \
          $(${{ inputs.sudo && 'sudo ' || '' }}docker ps --filter name=${{ inputs.container_name }} -q) \
          erddap_deploy \
          ${{ inputs.datasets_xml && '--datasets-xml=' || '' }}${{ inputs.datasets_xml }} \
          ${{ inputs.recursive && '--recursive' || '' }} \
          ${{ inputs.active_datasets_xml && '--active-datasets-xml=' || '' }}${{ inputs.active_datasets_xml }} \
          ${{ inputs.big_parent_directory && '--big-parent-directory=' || '' }}${{ inputs.bigParentDirectory }} \
          sync \
          ${{ inputs.repo && '--repo=' || '' }}${{ inputs.repo }} \
          ${{ inputs.branch && '--branch=' || '' }}${{ inputs.branch }} \
          ${{ inputs.pull && '--pull' || '' }} \
          ${{ inputs.local_repo_path && '--local-repo-path=' || '' }}${{ inputs.local_repo_path }} \
          ${{ inputs.hard_flag && '--hard-flag' || '' }} \
          ${{ inputs.hard_flag_dir && '--hard-flag-dir=' || '' }}${{ inputs.hard_flag_dir }} \
          ${{ inputs.monitor && 'monitor' || '' }};

