# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  run_erddap_checks:
    runs-on: ubuntu-latest
    name: Test erddap_checks action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0
      - name: run erddap_predeployment-checks
        id: erddap_deploy
        uses: ./test-datasets-xml.yml # Uses an action in the root directory
        with:
          datasets_xml: tests/data/datasets.d/*.xml