name: Test Action
on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test erddap_deploy/test action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
            fetch-depth: 0
      - name: See what's in the directory
        run: ls -R
      - name: run erddap_deploy test action
        id: erddap_deploy
        uses: ./actions/test
        with:
          datasets_xml: tests/data/datasets.d/*.xml